################################################################################
# Copyright 2017 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 1.1.0
# Author: "Gijs Paulides" <gijs.paulides@spritecloud.com>
require 'lapis_lazuli'
require 'lapis_lazuli/cucumber'

LapisLazuli::WorldModule::Config.config_file = "config/config.yml"
World(LapisLazuli)

# Do something when LapisLazuli is started (This is before the browser is opened)
LapisLazuli.Start do
  # Print gem information
  print "---- VERSION INFO ----\n"
  print "Lapis Lazuli: #{Gem.loaded_specs['lapis_lazuli'].version}\n"
  print "Selenium webdriver: #{Gem.loaded_specs['selenium-webdriver'].version}\n"
  print "Watir: #{Gem.loaded_specs['watir'].version}\n"
  print "---- VERSION INFO ----\n\n"
  #If BROWSER is NIL, Lapis Lazuli will default to Firefox
  if !ENV['BROWSER'] || ENV['BROWSER'] == 'firefox'

    # Get Selenium to create a profile object
    require 'selenium-webdriver'
    profile = Selenium::WebDriver::Firefox::Profile.new

    # These settings prevent a warning after authenticating via URL
    # For example user:pass@https://website.com/
    profile['network.http.phishy-userpass-length'] = 255
    profile['network.http.use-cache'] = false

    # Start the browser with these settings
    browser :firefox, :profile => profile

  end
end